// Code generated by ent, DO NOT EDIT.

package serp

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the serp type in the database.
	Label = "serp"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPhones holds the string denoting the phones field in the database.
	FieldPhones = "phones"
	// FieldEmails holds the string denoting the emails field in the database.
	FieldEmails = "emails"
	// FieldKeyWords holds the string denoting the key_words field in the database.
	FieldKeyWords = "key_words"
	// FieldIsRead holds the string denoting the is_read field in the database.
	FieldIsRead = "is_read"
	// FieldSqID holds the string denoting the sq_id field in the database.
	FieldSqID = "sq_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSearchQuery holds the string denoting the search_query edge name in mutations.
	EdgeSearchQuery = "search_query"
	// Table holds the table name of the serp in the database.
	Table = "serps"
	// SearchQueryTable is the table that holds the search_query relation/edge.
	SearchQueryTable = "serps"
	// SearchQueryInverseTable is the table name for the SearchQuery entity.
	// It exists in this package in order to avoid circular dependency with the "searchquery" package.
	SearchQueryInverseTable = "search_queries"
	// SearchQueryColumn is the table column denoting the search_query relation/edge.
	SearchQueryColumn = "sq_id"
)

// Columns holds all SQL columns for serp fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldTitle,
	FieldDescription,
	FieldPhones,
	FieldEmails,
	FieldKeyWords,
	FieldIsRead,
	FieldSqID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultIsRead holds the default value on creation for the "is_read" field.
	DefaultIsRead bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SERP queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIsRead orders the results by the is_read field.
func ByIsRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRead, opts...).ToFunc()
}

// BySqID orders the results by the sq_id field.
func BySqID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSqID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySearchQueryField orders the results by search_query field.
func BySearchQueryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSearchQueryStep(), sql.OrderByField(field, opts...))
	}
}
func newSearchQueryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SearchQueryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SearchQueryTable, SearchQueryColumn),
	)
}
