// Code generated by ent, DO NOT EDIT.

package serp

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/karust/openserp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SERP {
	return predicate.SERP(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SERP {
	return predicate.SERP(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SERP {
	return predicate.SERP(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SERP {
	return predicate.SERP(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SERP {
	return predicate.SERP(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SERP {
	return predicate.SERP(sql.FieldLTE(FieldID, id))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldURL, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldDescription, v))
}

// IsRead applies equality check predicate on the "is_read" field. It's identical to IsReadEQ.
func IsRead(v bool) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldIsRead, v))
}

// SqID applies equality check predicate on the "sq_id" field. It's identical to SqIDEQ.
func SqID(v int) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldSqID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldCreatedAt, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.SERP {
	return predicate.SERP(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.SERP {
	return predicate.SERP(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.SERP {
	return predicate.SERP(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.SERP {
	return predicate.SERP(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.SERP {
	return predicate.SERP(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.SERP {
	return predicate.SERP(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.SERP {
	return predicate.SERP(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.SERP {
	return predicate.SERP(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.SERP {
	return predicate.SERP(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.SERP {
	return predicate.SERP(sql.FieldContainsFold(FieldURL, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SERP {
	return predicate.SERP(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SERP {
	return predicate.SERP(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SERP {
	return predicate.SERP(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SERP {
	return predicate.SERP(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SERP {
	return predicate.SERP(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SERP {
	return predicate.SERP(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SERP {
	return predicate.SERP(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SERP {
	return predicate.SERP(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SERP {
	return predicate.SERP(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SERP {
	return predicate.SERP(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SERP {
	return predicate.SERP(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SERP {
	return predicate.SERP(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SERP {
	return predicate.SERP(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SERP {
	return predicate.SERP(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SERP {
	return predicate.SERP(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SERP {
	return predicate.SERP(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SERP {
	return predicate.SERP(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SERP {
	return predicate.SERP(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SERP {
	return predicate.SERP(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SERP {
	return predicate.SERP(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SERP {
	return predicate.SERP(sql.FieldContainsFold(FieldDescription, v))
}

// PhonesIsNil applies the IsNil predicate on the "phones" field.
func PhonesIsNil() predicate.SERP {
	return predicate.SERP(sql.FieldIsNull(FieldPhones))
}

// PhonesNotNil applies the NotNil predicate on the "phones" field.
func PhonesNotNil() predicate.SERP {
	return predicate.SERP(sql.FieldNotNull(FieldPhones))
}

// EmailsIsNil applies the IsNil predicate on the "emails" field.
func EmailsIsNil() predicate.SERP {
	return predicate.SERP(sql.FieldIsNull(FieldEmails))
}

// EmailsNotNil applies the NotNil predicate on the "emails" field.
func EmailsNotNil() predicate.SERP {
	return predicate.SERP(sql.FieldNotNull(FieldEmails))
}

// IsReadEQ applies the EQ predicate on the "is_read" field.
func IsReadEQ(v bool) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldIsRead, v))
}

// IsReadNEQ applies the NEQ predicate on the "is_read" field.
func IsReadNEQ(v bool) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldIsRead, v))
}

// SqIDEQ applies the EQ predicate on the "sq_id" field.
func SqIDEQ(v int) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldSqID, v))
}

// SqIDNEQ applies the NEQ predicate on the "sq_id" field.
func SqIDNEQ(v int) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldSqID, v))
}

// SqIDIn applies the In predicate on the "sq_id" field.
func SqIDIn(vs ...int) predicate.SERP {
	return predicate.SERP(sql.FieldIn(FieldSqID, vs...))
}

// SqIDNotIn applies the NotIn predicate on the "sq_id" field.
func SqIDNotIn(vs ...int) predicate.SERP {
	return predicate.SERP(sql.FieldNotIn(FieldSqID, vs...))
}

// SqIDIsNil applies the IsNil predicate on the "sq_id" field.
func SqIDIsNil() predicate.SERP {
	return predicate.SERP(sql.FieldIsNull(FieldSqID))
}

// SqIDNotNil applies the NotNil predicate on the "sq_id" field.
func SqIDNotNil() predicate.SERP {
	return predicate.SERP(sql.FieldNotNull(FieldSqID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SERP {
	return predicate.SERP(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSearchQuery applies the HasEdge predicate on the "search_query" edge.
func HasSearchQuery() predicate.SERP {
	return predicate.SERP(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SearchQueryTable, SearchQueryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSearchQueryWith applies the HasEdge predicate on the "search_query" edge with a given conditions (other predicates).
func HasSearchQueryWith(preds ...predicate.SearchQuery) predicate.SERP {
	return predicate.SERP(func(s *sql.Selector) {
		step := newSearchQueryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SERP) predicate.SERP {
	return predicate.SERP(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SERP) predicate.SERP {
	return predicate.SERP(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SERP) predicate.SERP {
	return predicate.SERP(sql.NotPredicates(p))
}
