// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/karust/openserp/ent/schema"
	"github.com/karust/openserp/ent/searchquery"
	"github.com/karust/openserp/ent/serp"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	serpFields := schema.SERP{}.Fields()
	_ = serpFields
	// serpDescURL is the schema descriptor for url field.
	serpDescURL := serpFields[0].Descriptor()
	// serp.URLValidator is a validator for the "url" field. It is called by the builders before save.
	serp.URLValidator = serpDescURL.Validators[0].(func(string) error)
	// serpDescTitle is the schema descriptor for title field.
	serpDescTitle := serpFields[1].Descriptor()
	// serp.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	serp.TitleValidator = serpDescTitle.Validators[0].(func(string) error)
	// serpDescIsRead is the schema descriptor for is_read field.
	serpDescIsRead := serpFields[6].Descriptor()
	// serp.DefaultIsRead holds the default value on creation for the is_read field.
	serp.DefaultIsRead = serpDescIsRead.Default.(bool)
	// serpDescCreatedAt is the schema descriptor for created_at field.
	serpDescCreatedAt := serpFields[8].Descriptor()
	// serp.DefaultCreatedAt holds the default value on creation for the created_at field.
	serp.DefaultCreatedAt = serpDescCreatedAt.Default.(func() time.Time)
	searchqueryFields := schema.SearchQuery{}.Fields()
	_ = searchqueryFields
	// searchqueryDescQuery is the schema descriptor for query field.
	searchqueryDescQuery := searchqueryFields[0].Descriptor()
	// searchquery.QueryValidator is a validator for the "query" field. It is called by the builders before save.
	searchquery.QueryValidator = searchqueryDescQuery.Validators[0].(func(string) error)
	// searchqueryDescIsCanceled is the schema descriptor for is_canceled field.
	searchqueryDescIsCanceled := searchqueryFields[3].Descriptor()
	// searchquery.DefaultIsCanceled holds the default value on creation for the is_canceled field.
	searchquery.DefaultIsCanceled = searchqueryDescIsCanceled.Default.(bool)
	// searchqueryDescCreatedAt is the schema descriptor for created_at field.
	searchqueryDescCreatedAt := searchqueryFields[4].Descriptor()
	// searchquery.DefaultCreatedAt holds the default value on creation for the created_at field.
	searchquery.DefaultCreatedAt = searchqueryDescCreatedAt.Default.(func() time.Time)
}
