// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/karust/openserp/ent/predicate"
	"github.com/karust/openserp/ent/searchquery"
	"github.com/karust/openserp/ent/serp"
)

// SERPQuery is the builder for querying SERP entities.
type SERPQuery struct {
	config
	ctx             *QueryContext
	order           []serp.OrderOption
	inters          []Interceptor
	predicates      []predicate.SERP
	withSearchQuery *SearchQueryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SERPQuery builder.
func (sq *SERPQuery) Where(ps ...predicate.SERP) *SERPQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SERPQuery) Limit(limit int) *SERPQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SERPQuery) Offset(offset int) *SERPQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SERPQuery) Unique(unique bool) *SERPQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SERPQuery) Order(o ...serp.OrderOption) *SERPQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QuerySearchQuery chains the current query on the "search_query" edge.
func (sq *SERPQuery) QuerySearchQuery() *SearchQueryQuery {
	query := (&SearchQueryClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serp.Table, serp.FieldID, selector),
			sqlgraph.To(searchquery.Table, searchquery.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, serp.SearchQueryTable, serp.SearchQueryColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SERP entity from the query.
// Returns a *NotFoundError when no SERP was found.
func (sq *SERPQuery) First(ctx context.Context) (*SERP, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serp.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SERPQuery) FirstX(ctx context.Context) *SERP {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SERP ID from the query.
// Returns a *NotFoundError when no SERP ID was found.
func (sq *SERPQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serp.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SERPQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SERP entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SERP entity is found.
// Returns a *NotFoundError when no SERP entities are found.
func (sq *SERPQuery) Only(ctx context.Context) (*SERP, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serp.Label}
	default:
		return nil, &NotSingularError{serp.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SERPQuery) OnlyX(ctx context.Context) *SERP {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SERP ID in the query.
// Returns a *NotSingularError when more than one SERP ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SERPQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serp.Label}
	default:
		err = &NotSingularError{serp.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SERPQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SERPs.
func (sq *SERPQuery) All(ctx context.Context) ([]*SERP, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SERP, *SERPQuery]()
	return withInterceptors[[]*SERP](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SERPQuery) AllX(ctx context.Context) []*SERP {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SERP IDs.
func (sq *SERPQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err = sq.Select(serp.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SERPQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SERPQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SERPQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SERPQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SERPQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SERPQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SERPQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SERPQuery) Clone() *SERPQuery {
	if sq == nil {
		return nil
	}
	return &SERPQuery{
		config:          sq.config,
		ctx:             sq.ctx.Clone(),
		order:           append([]serp.OrderOption{}, sq.order...),
		inters:          append([]Interceptor{}, sq.inters...),
		predicates:      append([]predicate.SERP{}, sq.predicates...),
		withSearchQuery: sq.withSearchQuery.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithSearchQuery tells the query-builder to eager-load the nodes that are connected to
// the "search_query" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SERPQuery) WithSearchQuery(opts ...func(*SearchQueryQuery)) *SERPQuery {
	query := (&SearchQueryClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withSearchQuery = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SERP.Query().
//		GroupBy(serp.FieldURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SERPQuery) GroupBy(field string, fields ...string) *SERPGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SERPGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = serp.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//	}
//
//	client.SERP.Query().
//		Select(serp.FieldURL).
//		Scan(ctx, &v)
func (sq *SERPQuery) Select(fields ...string) *SERPSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SERPSelect{SERPQuery: sq}
	sbuild.label = serp.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SERPSelect configured with the given aggregations.
func (sq *SERPQuery) Aggregate(fns ...AggregateFunc) *SERPSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SERPQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !serp.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SERPQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SERP, error) {
	var (
		nodes       = []*SERP{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withSearchQuery != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SERP).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SERP{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withSearchQuery; query != nil {
		if err := sq.loadSearchQuery(ctx, query, nodes, nil,
			func(n *SERP, e *SearchQuery) { n.Edges.SearchQuery = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SERPQuery) loadSearchQuery(ctx context.Context, query *SearchQueryQuery, nodes []*SERP, init func(*SERP), assign func(*SERP, *SearchQuery)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SERP)
	for i := range nodes {
		fk := nodes[i].SqID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(searchquery.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sq_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *SERPQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SERPQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(serp.Table, serp.Columns, sqlgraph.NewFieldSpec(serp.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serp.FieldID)
		for i := range fields {
			if fields[i] != serp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sq.withSearchQuery != nil {
			_spec.Node.AddColumnOnce(serp.FieldSqID)
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SERPQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(serp.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = serp.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SERPGroupBy is the group-by builder for SERP entities.
type SERPGroupBy struct {
	selector
	build *SERPQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SERPGroupBy) Aggregate(fns ...AggregateFunc) *SERPGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SERPGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SERPQuery, *SERPGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SERPGroupBy) sqlScan(ctx context.Context, root *SERPQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SERPSelect is the builder for selecting fields of SERP entities.
type SERPSelect struct {
	*SERPQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SERPSelect) Aggregate(fns ...AggregateFunc) *SERPSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SERPSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SERPQuery, *SERPSelect](ctx, ss.SERPQuery, ss, ss.inters, v)
}

func (ss *SERPSelect) sqlScan(ctx context.Context, root *SERPQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
