// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/karust/openserp/ent/searchquery"
	"github.com/karust/openserp/ent/serp"
)

// SERP is the model entity for the SERP schema.
type SERP struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Phones holds the value of the "phones" field.
	Phones []string `json:"phones,omitempty"`
	// Emails holds the value of the "emails" field.
	Emails []string `json:"emails,omitempty"`
	// KeyWords holds the value of the "key_words" field.
	KeyWords []string `json:"key_words,omitempty"`
	// IsRead holds the value of the "is_read" field.
	IsRead bool `json:"is_read,omitempty"`
	// SqID holds the value of the "sq_id" field.
	SqID int `json:"sq_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SERPQuery when eager-loading is set.
	Edges        SERPEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SERPEdges holds the relations/edges for other nodes in the graph.
type SERPEdges struct {
	// SearchQuery holds the value of the search_query edge.
	SearchQuery *SearchQuery `json:"search_query,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SearchQueryOrErr returns the SearchQuery value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SERPEdges) SearchQueryOrErr() (*SearchQuery, error) {
	if e.SearchQuery != nil {
		return e.SearchQuery, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: searchquery.Label}
	}
	return nil, &NotLoadedError{edge: "search_query"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SERP) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serp.FieldPhones, serp.FieldEmails, serp.FieldKeyWords:
			values[i] = new([]byte)
		case serp.FieldIsRead:
			values[i] = new(sql.NullBool)
		case serp.FieldID, serp.FieldSqID:
			values[i] = new(sql.NullInt64)
		case serp.FieldURL, serp.FieldTitle, serp.FieldDescription:
			values[i] = new(sql.NullString)
		case serp.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SERP fields.
func (s *SERP) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serp.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case serp.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				s.URL = value.String
			}
		case serp.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				s.Title = value.String
			}
		case serp.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				s.Description = value.String
			}
		case serp.FieldPhones:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field phones", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.Phones); err != nil {
					return fmt.Errorf("unmarshal field phones: %w", err)
				}
			}
		case serp.FieldEmails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field emails", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.Emails); err != nil {
					return fmt.Errorf("unmarshal field emails: %w", err)
				}
			}
		case serp.FieldKeyWords:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field key_words", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &s.KeyWords); err != nil {
					return fmt.Errorf("unmarshal field key_words: %w", err)
				}
			}
		case serp.FieldIsRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_read", values[i])
			} else if value.Valid {
				s.IsRead = value.Bool
			}
		case serp.FieldSqID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sq_id", values[i])
			} else if value.Valid {
				s.SqID = int(value.Int64)
			}
		case serp.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SERP.
// This includes values selected through modifiers, order, etc.
func (s *SERP) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QuerySearchQuery queries the "search_query" edge of the SERP entity.
func (s *SERP) QuerySearchQuery() *SearchQueryQuery {
	return NewSERPClient(s.config).QuerySearchQuery(s)
}

// Update returns a builder for updating this SERP.
// Note that you need to call SERP.Unwrap() before calling this method if this SERP
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *SERP) Update() *SERPUpdateOne {
	return NewSERPClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the SERP entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *SERP) Unwrap() *SERP {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: SERP is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *SERP) String() string {
	var builder strings.Builder
	builder.WriteString("SERP(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("url=")
	builder.WriteString(s.URL)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(s.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(s.Description)
	builder.WriteString(", ")
	builder.WriteString("phones=")
	builder.WriteString(fmt.Sprintf("%v", s.Phones))
	builder.WriteString(", ")
	builder.WriteString("emails=")
	builder.WriteString(fmt.Sprintf("%v", s.Emails))
	builder.WriteString(", ")
	builder.WriteString("key_words=")
	builder.WriteString(fmt.Sprintf("%v", s.KeyWords))
	builder.WriteString(", ")
	builder.WriteString("is_read=")
	builder.WriteString(fmt.Sprintf("%v", s.IsRead))
	builder.WriteString(", ")
	builder.WriteString("sq_id=")
	builder.WriteString(fmt.Sprintf("%v", s.SqID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SERPs is a parsable slice of SERP.
type SERPs []*SERP
