// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SERP is the predicate function for serp builders.
type SERP func(*sql.Selector)

// SearchQuery is the predicate function for searchquery builders.
type SearchQuery func(*sql.Selector)
